# Generated by Django 5.0.6 on 2024-05-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(default='none.png', upload_to='media/'),
        ),
    ]
