# Generated by Django 5.0.6 on 2024-05-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_alter_tutorial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='image',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutor',
            field=models.FileField(default='none.png', upload_to='media/'),
        ),
    ]
